apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: senk0.com
spec:
  secretName: senk0.com-tls
  dnsNames:
  - senk0.com
  - www.senk0.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
