apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobbleverse
  labels:
    app: cobbleverse
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: cobbleverse
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cobbleverse
    spec:
      containers:
      - image: itzg/minecraft-server:java21
        name: minecraft
        stdin: true
        tty: true
        env:
        - name: EULA
          value: "TRUE"
        - name: SKIP_SERVER_PROPERTIES
          value: "true"
        - name: TYPE
          value: "MODRINTH"
        - name: MODRINTH_MODPACK
          value: cobbleverse
        - name: MODRINTH_LOADER
          value: fabric
        - name: VERSION
          value: "1.21.1"
        - name: MODRINTH_VERSION
          value: "1.7.42"
        - name: MODRINTH_PROJECTS
          value: "configurable:3.5.2"
        - name: MODRINTH_EXCLUDE_FILES
          value: "c2me"
        - name: MODRINTH_FORCE_SYNCHRONIZE
          value: "true"
        - name: MEMORY
          value: "8G"
        - name: USE_AIKAR_FLAGS
          value: "true"
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: server-properties
          mountPath: /data/server.properties
          subPath: server.properties
        ports:
        - containerPort: 25565
          protocol: TCP
        startupProbe:
          exec:
            command: ["mc-health"]
          initialDelaySeconds: 120
          periodSeconds: 15
          failureThreshold: 120
        readinessProbe:
          exec:
            command: ["mc-health"]
          periodSeconds: 30
          failureThreshold: 3
        resources:
          limits:
            cpu: "8"
            memory: 11Gi
          requests:
            cpu: 500m
            memory: 9Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-cobbleverse
          readOnly: false
      - name: server-properties
        configMap:
          name: cobbleverse-server-properties

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-cobbleverse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: rook-rbd
  volumeMode: Filesystem
