apiVersion: v1
kind: Service
metadata:
  name: cobbleverse
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  selector:
    app: cobbleverse
  type: LoadBalancer
  loadBalancerIP: 10.1.1.105
  ports:
  - protocol: TCP
    name: "25565tcp"
    port: 25565
    targetPort: 25565
