# szurubooru-deployments.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: szurubooru/server:latest
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_USER
          value: "senk0"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: THREADS
          value: "2"
        - name: POSTGRES_DB
          value: "senk0"
        - name: LOG_SQL
          value: "0"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /opt/app/config.yaml
          subPath: config.yaml
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: szurubooru-data-pvc
      - name: config
        configMap:
          name: szurubooru-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: szurubooru-config
data:
  config.yaml: |
    database:
      host: postgres
      port: 5432
      user: senk0
      password: 1234
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: szurubooru-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Adjust as needed
