apiVersion: v1
kind: Service
metadata:
  name: ceph-access
  namespace: rook-ceph
spec:
  selector:
    app: ceph-access
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 31109
  type: NodePort
