apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gravity
  labels:
    app: homer
spec:
  replicas: 1 # Important: Add replicas!  StatefulSets require this.
  serviceName: "gravity"
  selector:
    matchLabels:
      app.kubernetes.io/name: gravity
  template: # This is where the pod template goes
    metadata:
      labels:
        app.kubernetes.io/name: gravity
    spec:
      containers:
        - name: gravity
          image: ghcr.io/beryju/gravity:stable
          env:
            - name: BOOTSTRAP_ROLES
              value: dns;dhcp;api;discovery;backup;monitoring;tsdb;tftp
            - name: INSTANCE_IP
              value: 10.0.1.52
            - name: INSTANCE_LISTEN
              value: 0.0.0.0
          ports:
            - containerPort: 53
              name: dns-tcp
            - containerPort: 53
              protocol: UDP
              name: dns-udp
            - containerPort: 67
              protocol: UDP
              name: dhcp
            - containerPort: 68
              protocol: UDP
              name: dhcp-alt
            - containerPort: 69
              protocol: UDP
              name: tftp
            - containerPort: 8008
              name: http
            - containerPort: 8009
              name: http-metrics
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: rook-cephfs
        resources:
          requests:
            storage: 1Gi