apiVersion: v1
kind: Service
metadata:
  name: valheim-modded
spec:
  selector:
    app: valheim-modded
  type: LoadBalancer
  loadBalancerIP: 10.1.1.104
  ports:
  - protocol: UDP
    name: "2456udp"
    port: 2456
    targetPort: 2456
  - protocol: UDP
    name: "2457udp"
    port: 2457
    targetPort: 2457
