apiVersion: apps/v1
kind: Deployment
metadata:
  name: szurubooru
  labels:
    app: szurubooru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: szurubooru
  template:
    metadata:
      labels:
        app: szurubooru
    spec:
      containers:
      - name: client
        image: szurubooru/client:latest
        env:
        - name: BACKEND_HOST
          value: localhost
        - name: BASE_URL
          value: "https://img.senk0.com" # Adjust as needed
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: true
      - name: server
        image: szurubooru/server:latest
        env:
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_USER
          value: "senk0"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: THREADS
          value: "2"
        - name: POSTGRES_DB
          value: "senk0"
        - name: POSTGRES_PORT
          value: "5853"
        - name: LOG_SQL
          value: "0"
        volumeMounts:
        - name: data
          mountPath: /data
      - name: postgres
        image: postgres:11-alpine
        env:
        - name: POSTGRES_USER
          value: "senk0"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "senk0"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5853
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: szurubooru-data-pvc
      - name: postgres-data
        persistentVolumeClaim:
          claimName: szurubooru-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: szurubooru-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: szurubooru-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem