apiVersion: v1
kind: Service
metadata:
  name: gravity
  namespace: gravity
  labels:
    app.kubernetes.io/name: gravity
spec:
  selector:
    app.kubernetes.io/name: gravity
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dnstcp
    - port: 67
      targetPort: 67
      name: dhcp
      protocol: UDP
    - port: 69
      targetPort: 69
      name: tftp
      protocol: UDP
    - port: 8008
      targetPort: 8008
      name: http
      protocol: TCP
  type: LoadBalancer