apiVersion: apps/v1 
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - image: lscr.io/linuxserver/radarr:latest
        name: radarr
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
        - name: media
          mountPath: /media
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        ports:
        - containerPort: 7878
        resources:
          limits:
            cpu: 2
            memory: 2048Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 150m
            memory: 256Mi
      nodeSelector: 
        kubernetes.io/hostname: k8sw4
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
          readOnly: false
      - name: data
        hostPath:
          path: /kubernetes/media/data
          type: DirectoryOrCreate
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
