apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-manifest
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/senk02/kubernetes-configs.git
        revision: HEAD
        directories:
          - path: manifests/*/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/senk02/kubernetes-configs.git
        path: '{{.path.path}}'
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{index .path.segments 1}}'
      syncPolicy: {}