apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-reader
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints", "services", "nodes", "nodes/stats", "nodes/proxy"]
  verbs: ["get", "list", "watch"]
# You might need to add more resources depending on your Prometheus configuration
# For example, to monitor deployments and other apps:
# - apiGroups: ["apps"]
#   resources: ["deployments", "statefulsets", "replicasets"]
#   verbs: ["get", "list", "watch"]
# To monitor nodes:
# - apiGroups: [""]
#   resources: ["nodes"]
#   verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring # Make sure this matches the namespace of your Prometheus service account
roleRef:
  kind: ClusterRole
  name: prometheus-reader
  apiGroup: rbac.authorization.k8s.io