apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filerun-password
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 8ee67c49-e6ed-4f00-a42e-51c0af804e60
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filerun-root-password
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 3661b508-ddc9-4f62-82cd-bea71f6b2fdd
        property: password