apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filerun-password
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 7bf3f563-06a3-41f1-980a-48bce94d4029
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filerun-root-password
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 879329c3-4367-4ff1-86c5-c62fed492e88
        property: password