apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission
data:
  PUID: "1000"
  PGID: "1000"
  VPN_SERVICE_PROVIDER: "mullvad"
  VPN_TYPE: "wireguard"
  SERVER_CITIES: "Chicago IL"
  WIREGUARD_ADDRESSES: "10.67.15.247/32"
  FIREWALL_INPUT_PORTS: "9091,9696"
  FIREWALL_OUTBOUND_SUBNETS: "10.96.0.0/12,10.244.0.0/16"
