apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      hostAliases:
      - ip: "10.102.61.120"
        hostnames: ["sonarr"]
      - ip: "10.107.140.162"
        hostnames: ["radarr"]
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        envFrom:
        - configMapRef:
            name: transmission
        env:
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: transmission
              key: password
        resources:
          limits:
            cpu: "500m"
            memory: 128Mi
          requests:
            cpu: 1m
            memory: 64Mi
        volumeMounts:
        - name: tun
          mountPath: /dev/net/tun
      - name: transmission
        image: lscr.io/linuxserver/transmission:latest
        envFrom:
        - configMapRef:
            name: transmission
        volumeMounts:
        - name: data
          mountPath: /downloads
          subPath: downloads
        - name: wg-config
          mountPath: /config
        ports:
        - containerPort: 9091
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
            ephemeral-storage: 64Mi
          requests:
            cpu: 1m
            memory: 64Mi
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:2.4.0
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
        - name: prowlarr-config
          mountPath: /config
        ports:
        - containerPort: 9696
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:v3.5.0
        ports:
        - containerPort: 8191
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
            ephemeral-storage: 1Gi
          requests:
            cpu: 10m
            memory: 256Mi
      securityContext:
        fsGroup: 1000
      volumes:
      - name: data
        hostPath:
          path: /var/mnt/media
          type: Directory
      - name: wg-config
        persistentVolumeClaim:
          claimName: transmission-wg-config
      - name: prowlarr-config
        persistentVolumeClaim:
          claimName: prowlarr-config
      - name: tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-wg-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-rbd
