apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kayro-nightly
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 89a1f661-f063-4bb3-815b-09051857775c
        property: password