apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kayro-nightly
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: cc5b8ac9-2344-4b89-9513-d2b40d1ff277
        property: password