apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - image: lscr.io/linuxserver/prowlarr:1.36.3
        name: prowlarr
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 9696
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-config
          readOnly: false
      securityContext:
        fsGroup: 1000
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
