apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-application
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true