apiVersion: dns.cloudflare.millstone.tech/v1alpha1
kind: Record
metadata:
  name: java
  annotations:
    crossplane.io/external-name: a5a86c3b982b551c1fd2096576201bf9/f5720854a9f8c6a7dacee135d6243260
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: default
  forProvider:
    zoneId: a5a86c3b982b551c1fd2096576201bf9
    name: java.senk0.com
    type: A
    content: 147.185.221.25
    ttl: 1
    proxied: false
