apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: uwufs
  namespace: rook-ceph
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 1
  dataPools:
    - name: replicated
      failureDomain: osd
      replicated:
        size: 1
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: false
    resources:
      limits:
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
