apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:12.0
        command: ["mariadbd", "--innodb-buffer-pool-size=512M", "--transaction-isolation=READ-COMMITTED", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--max-connections=512", "--innodb-rollback-on-timeout=OFF", "--innodb-lock-wait-timeout=120"]
        env:
        - name: MARIADB_AUTO_UPGRADE
          value: "1"
        - name: MARIADB_INITDB_SKIP_TZINFO
          value: "1"
        - name: MARIADB_DATABASE
          value: "photoprism"
        - name: MARIADB_USER
          value: "photoprism"
        - name: MARIADB_PASSWORD
          value: "insecure"
        - name: MARIADB_ROOT_PASSWORD
          value: "insecure"
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
