apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lumyx
  name: lumyx
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: lumyx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lumyx
    spec:
      containers:
      - image: registry.senk0.com/lumyx:latest
        imagePullPolicy: Always
        name: lumyx
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 4Gi
            memory: 4Gi
          requests:
            cpu: 10m
            memory: 256Mi
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: lumyx
              key: password
        - name: SZURUBOORU_TOKEN
          valueFrom:
            secretKeyRef:
              name: szurubooru-api
              key: password
        - name: TARGET_CHANNEL_ID
          value: "1354200614506201293"
        - name: SZURUBOORU_API_URL
          value: "https://lumyx.senk0.com/api/posts?query=safety:safe&order=created&limit=1"
        - name: INTERVAL_SECONDS
          value: "20"
      restartPolicy: Always