apiVersion: v1
kind: Service
metadata:
  name: mqtt2prometheus
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9641"
spec:
  selector:
    app: mqtt2prometheus
  ports:
  - protocol: TCP
    port: 9641
    targetPort: 9641
    nodePort: 31121
  type: NodePort
