apiVersion: apps/v1 
kind: Deployment
metadata:
  name: adguard
  labels:
    app: adguard
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
      - image: adguard/adguardhome:v0.107.74
        name: adguard
        volumeMounts:
        - name: config 
          mountPath: /opt/adguardhome/conf
        - name: work
          mountPath: /opt/adguardhome/work
        ports:
        - containerPort: 80
        - containerPort: 3000
        - containerPort: 853
        - containerPort: 443
        - containerPort: 784
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
            ephemeral-storage: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      volumes:
      - name: work
        persistentVolumeClaim:
          claimName: adguard-workdir
          readOnly: false
      - name: config
        persistentVolumeClaim:
          claimName: adguard-config
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-cephfs
  volumeName: pvc-cd0fef94-a47c-4834-bea6-7f6c6946f797
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-workdir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi 
  storageClassName: rook-cephfs
  volumeName: pvc-fdef169d-cbe0-4b6a-be4f-393807bf2d12
  volumeMode: Filesystem
