apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs2-dedicated
  labels:
    app: cs2-dedicated
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: cs2-dedicated
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cs2-dedicated
    spec:
      initContainers:
      - name: change-volume-ownership
        image: busybox:1.36
        command: ["sh", "-c", "chown -R 1000:1000 /home/steam/cs2-dedicated"]
        volumeMounts:
        - name: cs2-data-nvme
          mountPath: /home/steam/cs2-dedicated
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      containers:
      - image: joedwards32/cs2:latest
        name: cs2-dedicated
        env:
        - name: SRCDS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: srcds-token
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: rcon-password
        - name: TV_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: tv-password
        - name: TV_RELAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: tv-relay-password
        - name: CS2_RCONPW
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: rcon-password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: mariadb-root-password
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: mariadb-password
        - name: SIMPLEADMIN_DISCORD_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: simpleadmin-discord-webhook
        - name: CS2_SERVERNAME
          value: "[NA] Twans HvH - Scout Only"
        - name: CS2_CFG_URL
          value: "https://github.com/Senk02/kubernetes-configs/raw/refs/heads/main/makko/csgo-hvh/scout-only-chi/cs2.cfg.tgz"
        - name: CS2_ADDITIONAL_ARGS
          value: "-insecure"
        volumeMounts:
        - name: cs2-data-nvme
          mountPath: /home/steam/cs2-dedicated
        - name: simpleadmin-config
          mountPath: /home/steam/cs2-dedicated/game/csgo/addons/counterstrikesharp/configs/plugins/CS2-SimpleAdmin/CS2-SimpleAdmin.json
          subPath: CS2-SimpleAdmin.json
        - name: plugin-configs
          mountPath: /home/steam/cs2-dedicated/game/csgo/addons/counterstrikesharp/configs/plugins/CS2-Essentials/CS2-Essentials.json
          subPath: CS2-Essentials.json
        - name: plugin-configs
          mountPath: /home/steam/cs2-dedicated/game/csgo/addons/counterstrikesharp/configs/plugins/MenuManagerCore/MenuManagerCore.json
          subPath: MenuManagerCore.json
        - name: plugin-configs
          mountPath: /home/steam/cs2-dedicated/game/csgo/addons/counterstrikesharp/configs/plugins/PlayerSettings/PlayerSettings.json
          subPath: PlayerSettings.json
        - name: plugin-configs
          mountPath: /home/steam/cs2-dedicated/game/csgo/addons/counterstrikesharp/configs/plugins/ResetScore/ResetScore.json
          subPath: ResetScore.json
        - name: plugin-configs
          mountPath: /home/steam/cs2-dedicated/game/csgo/addons/counterstrikesharp/configs/plugins/TeleportFix/TeleportFix.json
          subPath: TeleportFix.json
        ports:
        - containerPort: 27015 # CS2_PORT
          name: cs2-tcp
          protocol: TCP
        - containerPort: 27015 # CS2_PORT
          name: cs2-udp
          protocol: UDP
        - containerPort: 27020 # TV_PORT
          name: cstv-udp
          protocol: UDP
        stdin: true
        tty: true
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 2Gi
      volumes:
      - name: cs2-data-nvme
        hostPath:
          path: /var/nvme/csgo-hvh
          type: DirectoryOrCreate
      - name: plugin-configs
        secret:
          secretName: cs2-server-secrets
      - name: simpleadmin-config
        secret:
          secretName: simpleadmin-config
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
