apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs2-dedicated
  labels:
    app: cs2-dedicated
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: cs2-dedicated
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cs2-dedicated
    spec:
      initContainers:
      - name: change-volume-ownership
        image: busybox:1.36 # A small image with basic utilities like chown
        command: ["sh", "-c", "chown -R 1000:1000 /home/steam/cs2-dedicated", "chown -R 1000:1000 /home/steam/cs2-dedicated-nvme"]
        volumeMounts:
        - name: cs2-data
          mountPath: /home/steam/cs2-dedicated
        - name: cs2-data-nvme
          mountPath: /home/steam/cs2-dedicated-nvme
        securityContext:
          runAsUser: 0 # Run as root to change ownership
          runAsGroup: 0
      containers:
      - image: joedwards32/cs2
        name: cs2-dedicated
        env:
        - name: SRCDS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: srcds-token
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: rcon-password
        - name: TV_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: tv-password
        - name: TV_RELAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: tv-relay-password
        - name: CS2_RCONPW
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: rcon-password
        - name: CS2_SERVERNAME
          value: "[NA] Twans HvH - Scout Only"
        - name: CS2_CFG_URL
          value: "https://github.com/Senk02/kubernetes-configs/raw/refs/heads/main/makko/csgo-hvh/scout-only-chi/cs2.cfg.tgz"
        - name: CS2_ADDITIONAL_ARGS
          value: "-insecure"
        volumeMounts:
        - name: cs2-data
          mountPath: /home/steam/cs2-dedicated-old/
        - name: cs2-data-nvme
          mountPath: /home/steam/cs2-dedicated/
        ports:
        - containerPort: 27015 # Value from ConfigMap: CS2_PORT
          name: cs2-tcp
          protocol: TCP
        - containerPort: 27015 # Value from ConfigMap: CS2_PORT
          name: cs2-udp
          protocol: UDP
        - containerPort: 27020 # Value from ConfigMap: TV_PORT
          name: cstv-udp
          protocol: UDP
        - containerPort: 27016 # This should correspond to the value of CS2_RCON_PORT
          name: rcon-tcp
          protocol: TCP
        stdin: true
        tty: true
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 2Gi
      volumes:
      - name: cs2-data
        hostPath:
          path: /var/mnt/csgo-hvh
          type: DirectoryOrCreate
      - name: cs2-data-nvme
        hostPath:
          path: /var/nvme/csgo-hvh
          type: DirectoryOrCreate
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
