apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs2-dedicated
  labels:
    app: cs2-dedicated
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: cs2-dedicated
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cs2-dedicated
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: joedwards32/cs2
        name: cs2-dedicated
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        envFrom:
        - configMapRef:
            name: cs2-dedicated-config
        env:
        - name: SRCDS_TOKEN
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: srcds-token
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: rcon-password
        - name: TV_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: tv-password
        - name: TV_RELAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cs2-server-secrets
              key: tv-relay-password
        volumeMounts:
        - name: cs2-data
          mountPath: /home/steam/cs2-dedicated
        - name: server-config
          mountPath: /home/steam/cs2-dedicated/game/csgo/cfg/server_default.cfg
          subPath: server_default.cfg
        ports:
        - containerPort: 27015
          name: cs2-tcp
          protocol: TCP
        - containerPort: 27015
          name: cs2-udp
          protocol: UDP
        - containerPort: 27020
          name: cstv-udp
          protocol: UDP
        - containerPort: 27016
          name: rcon-tcp
          protocol: TCP
        stdin: true
        tty: true
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi
      volumes:
      - name: cs2-data
        persistentVolumeClaim:
          claimName: cs2-pvc
          readOnly: false
      - name: server-config
        configMap:
          name: cs2-server-config
          defaultMode: 0644
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cs2-pvc
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem