apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cs2-server-secrets
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: rcon-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 8629fd63-9129-448c-83ce-038602419917
        property: password
    - secretKey: tv-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 0c9222b9-bb50-4a67-9224-b96b06e6e14f
        property: password
    - secretKey: tv-relay-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d7888837-6237-4ff6-9cc4-0ea6f27ba7d7
        property: password
    - secretKey: srcds-token
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7b696e00-25b6-4549-baf4-f98518d90cd7
        property: password
    - secretKey: simpleadmin-discord-webhook
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 514e470b-a3af-46ba-b645-c472a5b34ac5
        property: password
    - secretKey: mariadb_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d5cfc33e-5b9b-4447-81ed-7d4b132129d9
        property: password