apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cs2-server-secrets
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore 
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: rcon-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7de08dba-6838-4a71-85a1-ac41d488fba9
        property: password
    - secretKey: tv-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7de08dba-6838-4a71-85a1-ac41d488fba9
        property: password
    - secretKey: tv-relay-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d99347df-472c-450a-81f4-e4dd73b8b838
        property: password
    - secretKey: srcds-token
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: fac227e6-4296-4446-8453-003134b378b2
        property: password