apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simpleadmin-config
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
    template:
      data:
        CS2-SimpleAdmin.json: |
          {
            "ConfigVersion": 24,
            "DatabaseHost": "mariadb",
            "DatabasePort": 3306,
            "DatabaseUser": "csgo-hvh",
            "DatabasePassword": "{{ .mariadb_password | toString }}",
            "DatabaseName": "csgo-hvh",
            "DatabaseSSlMode": "preferred",
            "OtherSettings": {
              "ShowActivityType": 2,
              "TeamSwitchType": 1,
              "KickTime": 5,
              "BanType": 1,
              "TimeMode": 1,
              "DisableDangerousCommands": true,
              "MaxBanDuration": 10080,
              "MaxMuteDuration": 10080,
              "ExpireOldIpBans": 0,
              "ReloadAdminsEveryMapChange": false,
              "DisconnectedPlayersHistoryCount": 10,
              "NotifyPenaltiesToAdminOnConnect": true,
              "ShowBanMenuIfNoTime": true,
              "UserMessageGagChatType": false,
              "CheckMultiAccountsByIp": true,
              "AdditionalCommandsToLog": [],
              "IgnoredIps": []
            },
            "EnableMetrics": true,
            "EnableUpdateCheck": true,
            "Timezone": "UTC",
            "WarnThreshold": {
              "998": "css_addban STEAMID64 60 \"3/4 Warn\"",
              "999": "css_ban #USERID 120 \"4/4 Warn\""
            },
            "MultiServerMode": true,
            "Discord": {
              "DiscordLogWebhook": "{{ .discord_webhook | toString }}",
              "DiscordPenaltyBanSettings": [
                {
                  "name": "Color",
                  "value": ""
                },
                {
                  "name": "Webhook",
                  "value": ""
                },
                {
                  "name": "ThumbnailUrl",
                  "value": ""
                },
                {
                  "name": "ImageUrl",
                  "value": ""
                },
                {
                  "name": "Footer",
                  "value": ""
                },
                {
                  "name": "Time",
                  "value": "{relative}"
                }
              ],
              "DiscordPenaltyMuteSettings": [
                {
                  "name": "Color",
                  "value": ""
                },
                {
                  "name": "Webhook",
                  "value": ""
                },
                {
                  "name": "ThumbnailUrl",
                  "value": ""
                },
                {
                  "name": "ImageUrl",
                  "value": ""
                },
                {
                  "name": "Footer",
                  "value": ""
                },
                {
                  "name": "Time",
                  "value": "{relative}"
                }
              ],
              "DiscordPenaltyGagSettings": [
                {
                  "name": "Color",
                  "value": ""
                },
                {
                  "name": "Webhook",
                  "value": ""
                },
                {
                  "name": "ThumbnailUrl",
                  "value": ""
                },
                {
                  "name": "ImageUrl",
                  "value": ""
                },
                {
                  "name": "Footer",
                  "value": ""
                },
                {
                  "name": "Time",
                  "value": "{relative}"
                }
              ],
              "DiscordPenaltySilenceSettings": [
                {
                  "name": "Color",
                  "value": ""
                },
                {
                  "name": "Webhook",
                  "value": ""
                },
                {
                  "name": "ThumbnailUrl",
                  "value": ""
                },
                {
                  "name": "ImageUrl",
                  "value": ""
                },
                {
                  "name": "Footer",
                  "value": ""
                },
                {
                  "name": "Time",
                  "value": "{relative}"
                }
              ],
              "DiscordPenaltyWarnSettings": [
                {
                  "name": "Color",
                  "value": ""
                },
                {
                  "name": "Webhook",
                  "value": ""
                },
                {
                  "name": "ThumbnailUrl",
                  "value": ""
                },
                {
                  "name": "ImageUrl",
                  "value": ""
                },
                {
                  "name": "Footer",
                  "value": ""
                },
                {
                  "name": "Time",
                  "value": "{relative}"
                }
              ]
            },
            "DefaultMaps": [],
            "WorkshopMaps": {},
            "CustomServerCommands": [],
            "MenuConfig": {
              "MenuType": "selectable",
              "Durations": [
                {
                  "name": "1 minute",
                  "duration": 1
                },
                {
                  "name": "5 minutes",
                  "duration": 5
                },
                {
                  "name": "15 minutes",
                  "duration": 15
                },
                {
                  "name": "1 hour",
                  "duration": 60
                },
                {
                  "name": "1 day",
                  "duration": 1440
                },
                {
                  "name": "7 days",
                  "duration": 10080
                },
                {
                  "name": "14 days",
                  "duration": 20160
                },
                {
                  "name": "30 days",
                  "duration": 43200
                },
                {
                  "name": "Permanent",
                  "duration": 0
                }
              ],
              "BanReasons": [
                "Hacking",
                "Voice Abuse",
                "Chat Abuse",
                "Admin disrespect",
                "Other"
              ],
              "KickReasons": [
                "Voice Abuse",
                "Chat Abuse",
                "Admin disrespect",
                "Other"
              ],
              "WarnReasons": [
                "Voice Abuse",
                "Chat Abuse",
                "Admin disrespect",
                "Other"
              ],
              "MuteReasons": [
                "Advertising",
                "Spamming",
                "Spectator camera abuse",
                "Hate",
                "Admin disrespect",
                "Other"
              ],
              "AdminFlags": [
                {
                  "name": "Generic",
                  "flag": "@css/generic"
                },
                {
                  "name": "Chat",
                  "flag": "@css/chat"
                },
                {
                  "name": "Change Map",
                  "flag": "@css/changemap"
                },
                {
                  "name": "Slay",
                  "flag": "@css/slay"
                },
                {
                  "name": "Kick",
                  "flag": "@css/kick"
                },
                {
                  "name": "Ban",
                  "flag": "@css/ban"
                },
                {
                  "name": "Perm Ban",
                  "flag": "@css/permban"
                },
                {
                  "name": "Unban",
                  "flag": "@css/unban"
                },
                {
                  "name": "Show IP",
                  "flag": "@css/showip"
                },
                {
                  "name": "Cvar",
                  "flag": "@css/cvar"
                },
                {
                  "name": "Rcon",
                  "flag": "@css/rcon"
                },
                {
                  "name": "Root (all flags)",
                  "flag": "@css/root"
                }
              ]
            }
          }
  data:
    - secretKey: mariadb_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6b3da1b0-d854-44fe-b902-c36ad6906cec
        property: password
    - secretKey: discord_webhook
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 86acabcb-be30-4070-81c8-4ce28e1723f5
        property: password
