apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: senk0-pkcs12-secret
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 42ee1743-7020-4763-b1ec-1bec0f1307ac
        property: password