apiVersion: apps/v1
kind: Deployment
metadata:
  name: archi
  labels:
    app: archi
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: archi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archi
    spec:
      containers:
      - image: justarchi/archisteamfarm
        name: archi
        volumeMounts:
        - name: config
          mountPath: /app/config
     #  - name: plugins
     #     mountPath: /app/plugins
        ports:
        - containerPort: 1242 
        resources:
          limits:
            cpu: 1
            memory: 256Mi
            ephemeral-storage: 128Mi
          requests:
            cpu: 10m
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: archi-config
          readOnly: false
     # - name: plugins
     #   nfs:
     #    server: 10.0.0.20
     #    path: /mnt/Pool1/ssd-storage/archi/plugins
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: archi-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
