apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:11.7
        name: mariadb
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: mariadb-root-password
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: mariadb-password
          - name: MARIADB_DATABASE
            value: "csgo-hvh"
          - name: MARIADB_USER
            value: "csgo-hvh"
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 10m
            memory: 128Mi
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem