apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-secrets
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: mariadb-root-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 0eced7e9-b10b-464d-a44e-39dddb18b991
        property: password
    - secretKey: mariadb-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6b3da1b0-d854-44fe-b902-c36ad6906cec
        property: password