apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-secrets
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: mariadb-root-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cd49b3b2-5fc3-467c-9e14-4a7a493aa5a1
        property: password
    - secretKey: mariadb-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: d5cfc33e-5b9b-4447-81ed-7d4b132129d9
        property: password