apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: routeros-credentials
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: credentials
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5ca9bc36-4c7a-42fc-a822-b0e7d644b72a
        property: password
