apiVersion: v1
kind: Secret
metadata:
  name: photoprism-secrets
stringData:
  PHOTOPRISM_ADMIN_PASSWORD: test
  PHOTOPRISM_DATABASE_DSN: username:password@tcp(db-server-address:3306)/dbname?charset=utf8mb4,utf8&parseTime=true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: photoprism
spec:
  selector:
    matchLabels:
      app: photoprism
  serviceName: photoprism
  replicas: 0
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        env:
        - name: PHOTOPRISM_DEBUG
          value: "true"
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: mysql
        - name: PHOTOPRISM_HTTP_HOST
          value: 0.0.0.0
        - name: PHOTOPRISM_HTTP_PORT
          value: "2342"
        # Load database DSN & admin password from secret
        envFrom:
        - secretRef:
            name: photoprism-secrets
            optional: false
        ports:
        - containerPort: 2342
          name: http
        volumeMounts:
        - name: originals
          mountPath: /photoprism/originals
        - name: import 
          mountPath: /photoprism/import
        - name: storage
          mountPath: /photoprism/storage
      volumes:
      - name: originals
        persistentVolumeClaim:
          claimName: originals-photoprism-pvc
          readOnly: false
      - name: import
        persistentVolumeClaim:
          claimName: import-photoprism-pvc
          readOnly: false
      - name: storage
        persistentVolumeClaim:
          claimName: storage-photoprism-pvc
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: originals-photoprism-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: import-photoprism-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-photoprism-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
