apiVersion: v1
kind: Service
metadata:
  name: satisfactory-skim
spec:
  selector:
    app: satisfactory-skim
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777
    nodePort: 32701
    name: "tcp"
  - protocol: UDP
    port: 7777
    targetPort: 7777
    nodePort: 32701
    name: "udp"
  type: NodePort

