apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: transmission
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6bdede16-4d1f-4c86-9d30-a1226e628b85
        property: password