apiVersion: dns.cloudflare.millstone.tech/v1alpha1
kind: Record
metadata:
  name: element
  annotations:
    crossplane.io/external-name: de4ede0e53c2d18a6ef30d713dcd7fa1
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: default
  forProvider:
    zoneId: a5a86c3b982b551c1fd2096576201bf9
    name: "element.senk0.com"
    type: A
    content: "73.208.200.98"
    ttl: 1
    proxied: false
