apiVersion: dns.cloudflare.millstone.tech/v1alpha1
kind: Record
metadata:
  name: mx-alt1
  annotations:
    crossplane.io/external-name: 4b9f2b9aabf840786000011e07571444
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: default
  forProvider:
    zoneId: a5a86c3b982b551c1fd2096576201bf9
    name: "senk0.com"
    type: MX
    content: "alt1.aspmx.l.google.com"
    ttl: 1
    proxied: false
    priority: 5
