apiVersion: dns.cloudflare.millstone.tech/v1alpha1
kind: Record
metadata:
  name: srv-mc-java
  annotations:
    crossplane.io/external-name: 91867e06de7dc18d5b8a135f0cd470d8
spec:
  deletionPolicy: Orphan
  managementPolicies: ["Observe", "Create", "Update", "Delete"]
  providerConfigRef:
    name: default
  forProvider:
    zoneId: a5a86c3b982b551c1fd2096576201bf9
    name: "_minecraft._tcp.mc.senk0.com"
    type: SRV
    ttl: 1
    proxied: false
    data:
      priority: 0
      weight: 0
      port: 60901
      target: "java.senk0.com"
