apiVersion: dns.cloudflare.millstone.tech/v1alpha1
kind: Record
metadata:
  name: wildcard
  annotations:
    crossplane.io/external-name: 885e663990c12e17ba11127e1cfb040f
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: default
  forProvider:
    zoneId: a5a86c3b982b551c1fd2096576201bf9
    name: "*.senk0.com"
    type: CNAME
    content: "dyn.senk0.com"
    ttl: 1
    proxied: false
