apiVersion: apps/v1 
kind: Deployment
metadata:
  name: satisfactory-skim
  labels:
    app: satisfactory-skim
spec:
  revisionHistoryLimit: 1
  replicas: 0
  selector:
    matchLabels:
      app: satisfactory-skim
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: satisfactory-skim
    spec:
      containers:
      - image: wolveix/satisfactory-server:latest
        name: satisfactory-skim
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
        - name: config 
          mountPath: /config
        ports:
        - containerPort: 7777
          protocol: TCP
        - containerPort: 7777
          protocol: UDP
        resources:
          limits:
            cpu: 2
            memory: 8Gi
            ephemeral-storage: 8Gi
          requests:
            cpu: 2
            memory: 6Gi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: satisfactory-skim-pvc
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: satisfactory-skim-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
