apiVersion: apps/v1 
kind: Deployment
metadata:
  name: duplicati
  labels:
    app: duplicati
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: duplicati
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: duplicati
    spec:
      containers:
      - image: duplicati/duplicati:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            /usr/bin/duplicati --webservice-interface=any --webservice-port=8200 & 
            apt-get install ceph-common ceph-fuse -y
        name: duplicati
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - containerPort: 8200
        resources:
          limits:
            cpu: 4
            memory: 4Gi
            ephemeral-storage: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: duplicati-data
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: duplicati-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
