---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pcbackup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
