apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
  - name: port1
    protocol: TCP
    port: 1883
    targetPort: 1883
    nodePort: 31122
  - name: port2
    protocol: TCP
    port: 9001
    targetPort: 9001
    nodePort: 31123
  type: NodePort