apiVersion: v1
kind: ConfigMap
metadata:
  name: guest-bastion-config
  namespace: guest-bastion
data:
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM/82T+Jgv4RP+UwMYWfI8IYqN/hi0EC4v9SbpSN2ALM admin@tiny
  forwarding.conf: |
    AllowTcpForwarding yes
