apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guest-bastion-config
  namespace: guest-bastion
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: rook-rbd
  resources:
    requests:
      storage: 1Gi
