apiVersion: v1
kind: Service
metadata:
  name: guest-bastion
  namespace: guest-bastion
  annotations:
    io.cilium/lb-ipam-ips: "10.1.1.150"
spec:
  type: LoadBalancer
  selector: { app: guest-bastion }
  ports:
    - { name: ssh, port: 22, targetPort: 2222, protocol: TCP }
