apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kayro-server
  name: kayro-server
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kayro-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kayro-server
    spec:
      containers:
      - image: registry.senk0.com/kayro-server:latest
        imagePullPolicy: Always
        name: kayro-server
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 4Gi
            memory: 4Gi
          requests:
            cpu: 10m
            memory: 256Mi
      - env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: kayro
              key: password
        - name: DISCORD_CHANNEL1
          value: "1348806785594556416"
        - name: DISCORD_CHANNEL2
          value: "1349211808568967332"
        - name: DISCORD_GUILD1
          value: "1126157503877623869"
        - name: DISCORD_GUILD2
          value: "596350022191415318"
        image: registry.senk0.com/kayro:latest
        imagePullPolicy: Always
        name: kayro
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 2