apiVersion: v1
kind: Service
metadata:
  name: sonyx-service
  labels:
    app: sonyx
spec:
  selector:
    app: sonyx
  ports:
    - protocol: TCP
      port: 4533
      targetPort: 4533
  type: ClusterIP