apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring # Or the namespace where you keep your monitoring components
  labels:
    app: node-exporter
    component: metrics
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
        component: metrics
    spec:
      hostPID: true # Required for some collectors to access host information
      hostNetwork: true # Recommended for simplicity, exposes metrics directly on the host network
      updateStrategy:
        type: RollingUpdate
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest # Consider using a specific version for stability
          ports:
            - containerPort: 9100
              hostPort: 9100
              protocol: TCP
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: rootfs
              mountPath: /host/root
              readOnly: true
          securityContext:
            privileged: true # Required for some collectors
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: rootfs
          hostPath:
            path: /