apiVersion: apps/v1 
kind: Deployment
metadata:
  name: boofcraft
  labels:
    app: boofcraft
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: boofcraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: boofcraft
    spec:
      containers:
      - image: itzg/minecraft-server:java8
        name: minecraft
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: "AUTO_CURSEFORGE"
        - name: VERSION
          value: "1.12.2"
        - name: MEMORY
          value: "8G"
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: curseforge-api-key
              key: password
        - name: CF_SLUG
          value: enigmatica2expert
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - containerPort: 25565
        resources:
          limits:
            cpu: "2"
            memory: 8192Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 100m
            memory: 2048Mi
            ephemeral-storage: 64Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-boofcraft
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-boofcraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
