apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: curseforge-api-key
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6a1b78a3-35bb-42f2-91c5-f9ec18a56b3d
        property: password