apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: curseforge-api-key
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 1dc913c4-0578-4c75-991b-4897ab60bdb3
        property: password