apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.28.0
        name: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 64Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
      - image: node:18-alpine
        name: metrics-proxy
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args:
          - |
            cp -L /app-config/* /app/ && npm install && node server.js
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus.monitoring.svc.cluster.local:9090"
        volumeMounts:
        - name: nodejs-app-config
          mountPath: /app-config
          readOnly: true
        - name: nodejs-app-workspace
          mountPath: /app
        ports:
        - containerPort: 3000
          name: metrics-proxy
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
            ephemeral-storage: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: nginx-pvc
          readOnly: false
      - name: nodejs-app-config
        configMap:
          name: metrics-proxy-app
      - name: nodejs-app-workspace
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-metrics-config
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-iem
  labels:
    app: nginx-iem
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: nginx-iem
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-iem
    spec:
      containers:
      - image: nginx:1.28.0
        name: nginx-iem
        volumeMounts:
        - name: html-iem
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 64Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
      volumes:
      - name: html-iem
        persistentVolumeClaim:
          claimName: nginx-iem-pvc
          readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-iem-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem