apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonyx-secrets
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: db-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: eef663a6-d5f6-4349-b9eb-da8cdc06f5b5
        property: password
    - secretKey: lastfm-api-key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 46f54c3d-8bc4-4575-bb2b-63182431acd0
        property: password
    - secretKey: lastfm-api-secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 1dd15a6e-fefb-4764-bb69-d9d30ab122f5
        property: password
    - secretKey: spotify-client-id
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 229deb4d-977a-4f31-94dd-e00e7259c583
        property: password
    - secretKey: spotify-client-secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2c7b190b-8b30-4b76-9959-cd40f6e4e742
        property: password
    - secretKey: youtube-api-key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: bf1b9797-8604-4541-846f-f2ec441be6cf
        property: password