apiVersion: apps/v1
kind: Deployment
metadata:
  name: szurubooru
  labels:
    app: szurubooru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: szurubooru
  template:
    metadata:
      labels:
        app: szurubooru
    spec:
      containers:
      - name: client
        image: szurubooru/client:latest
        env:
        - name: BACKEND_HOST
          value: localhost
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 20m
            memory: 64Mi
            ephemeral-storage: 16Mi
      - name: server
        image: szurubooru/server:latest
        env:
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_USER
          value: "senk0"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: THREADS
          value: "2"
        - name: POSTGRES_DB
          value: "senk0"
        - name: POSTGRES_PORT
          value: "5432"
        - name: LOG_SQL
          value: "0"
        resources:
          limits:
            cpu: 100m
            memory: 768Mi
            ephemeral-storage: 128Mi
          requests:
            cpu: 20m
            memory: 64Mi
            ephemeral-storage: 16Mi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /opt/app/config.yaml
          subPath: config.yaml
      - name: postgres
        image: postgres:11.22-alpine
        env:
        - name: POSTGRES_USER
          value: "senk0"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "senk0"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 10m
            memory: 64Mi
            ephemeral-storage: 16Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: szurubooru-data-pvc
      - name: postgres-data
        persistentVolumeClaim:
          claimName: szurubooru-postgres-pvc
      - name: config
        persistentVolumeClaim:
          claimName: szurubooru-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: szurubooru-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: szurubooru-postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: szurubooru-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
