apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonyx-secrets
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: db-password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: fe6cb510-6a8c-44e0-89eb-5b9ba15055a3
        property: password
    - secretKey: lastfm-api-key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2926a21b-7c48-4d88-b142-7b2236da1244
        property: password
    - secretKey: lastfm-api-secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2e2d12d1-43e4-4f39-8d7d-dd07b8dc4182
        property: password
    - secretKey: spotify-client-id
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 005bc750-3fdc-4ff0-a76b-cf0b7f291abe
        property: password
    - secretKey: spotify-client-secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: f77c8347-6294-4110-8fa2-c4428edb7389
        property: password
    - secretKey: youtube-api-key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 208b637e-6084-4746-b08a-b199fd54137b
        property: password