apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 10f7fb39-6b57-4a56-9cde-ec0b193bcb59
        property: password