apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: bbd4c5dd-645f-433d-8676-5dcc9832fa82
        property: password