apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt2prometheus
  labels:
    app: mqtt2prometheus
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: mqtt2prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mqtt2prometheus
    spec:
      containers:
      - image: ghcr.io/hikhvar/mqtt2prometheus:latest
        name: mqtt2prometheus
        volumeMounts:
        - name: config
          mountPath: /config.yaml
          subPath: "config.yaml"
        ports:
        - containerPort: 9641
        resources:
          limits:
            cpu: 1
            memory: 128Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: mqtt2prometheus-config
          readOnly: false
      securityContext:
        fsGroup: 0
        runAsUser: 0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mqtt2prometheus-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
