apiVersion: v1
kind: Service
metadata:
  name: monifactory
spec:
  selector:
    app: monifactory
  type: LoadBalancer
  loadBalancerIP: 10.1.1.106
  ports:
  - protocol: TCP
    name: "25565tcp"
    port: 25565
    targetPort: 25565
