apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool-ssd
  namespace: rook-ceph
spec:
  failureDomain: host
  deviceClass: ssd
  replicated:
    size: 3
  parameters:
    compression_mode: none
