apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: uwufs
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    deviceClass: ssd
    replicated:
      size: 3
  dataPools:
    - name: replicated
      failureDomain: host
      deviceClass: ssd
      replicated:
        size: 3
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
    resources:
      limits:
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
