apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: xwxfs
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: osd
    replicated:
      size: 1
  dataPools:
    - name: replicated
      failureDomain: osd
      deviceClass: nvme
      replicated:
        size: 1
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
    resources:
      limits:
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"