apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  labels:
    app: synapse
spec:
  selector:
    matchLabels:
      app: synapse
  replicas: 1
  template:
    metadata:
      labels:
        app: synapse
    spec:
      initContainers:
      - name: synapse-generate
        image: matrixdotorg/synapse:v1.130.0
        env:
          - name: SYNAPSE_SERVER_NAME
            value: "element.senk0.com"
          - name: SYNAPSE_REPORT_STATS
            value: "no"
          - name: SYNAPSE_PUBLIC_BASEURL  # Add this line
            value: "https://element.senk0.com"
        args: ["generate"]
        volumeMounts:
        - mountPath: /data
          name: synapse-data
      containers:
      - name: synapse
        image: matrixdotorg/synapse:v1.130.0
        env:
          - name: "TZ"
            value: "America/Chicago"
        ports:
        - containerPort: 8008
        volumeMounts:
        - mountPath: /data
          name: synapse-data
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
            ephemeral-storage: 128Mi
          requests:
            cpu: 256m
            memory: 512Mi
            ephemeral-storage: 16Mi
      volumes:
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: synapse-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
