apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: szurubooru-api
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: f131c7c1-6911-45c0-818f-f1477247b54c
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lumyx
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 1475ebc3-3823-4140-bc9b-2036a021b082
        property: password