apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: szurubooru-api
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: 26615cf6-69d7-45aa-8604-b3faa1df3d94
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lumyx
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    creationPolicy: Owner
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: ca79b4b9-ba18-416e-8ba4-2a3f616b0920
        property: password