apiVersion: ip.routeros.sindrip.io/v1alpha1
kind: FirewallNAT
metadata:
  name: nat-monifactory
  annotations:
    crossplane.io/external-name: "monifactory mc"
spec:
  managementPolicies: ["Observe"]
  deletionPolicy: Orphan
  providerConfigRef:
    name: default
  forProvider:
    comment: "monifactory mc"
    chain: dstnat
    action: dst-nat
    protocol: tcp
    inInterface: ether2
    dstPort: "49566"
    toAddresses: 10.1.1.106
    toPorts: "25565"
