apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-key-config
  namespace: rook-ceph
data:
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID4kBOtzxE7P6VEWVQRnKLCaq+4OT5JXxQS7x6+zgFuh senk0@alpine
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH4AWCmnv+IHVGUFGTdsMK4FCh3fEunBdWKKp1eBPh9C senk0@DESKTOP-IB3KU35
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBsRDVdcOVgfpDL9AYLnbrlsJpLQPLRJ6Ac/4ClXP80/ admin@senk0.com