apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-access-owo
  namespace: rook-ceph
  labels:
    app: ceph-access-owo
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ceph-access-owo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-access-owo
    spec:
      containers:
      - image: senk02/ceph-access:latest
        name: ceph-access-owo
        env:
          - name: CEPHFS_USER
            valueFrom:
              configMapKeyRef:
                name: ceph-access-configmap
                key: CEPHFS_USER
          - name: CEPHFS_FS
            valueFrom:
              configMapKeyRef:
                name: ceph-access-configmap
                key: CEPHFS_FS
          - name: CEPHFS_MON_ADDR
            valueFrom:
              configMapKeyRef:
                name: ceph-access-configmap
                key: CEPHFS_MON_ADDR
        volumeMounts:
          - name: ceph-auth-key
            mountPath: "/secret"
            subPath: secret
            readOnly: true
        ports:
        - containerPort: 22
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
              - MKNOD
        resources:
          limits:
            cpu: 2
            memory: 8Gi
            ephemeral-storage: 20Gi
          requests:
            cpu: 10m
            memory: 4Gi
      volumes:
      - name: ceph-auth-key
        secret:
          secretName: ceph-auth-key
          items:
          - key: secretfile
            path: secret
