apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-access-awa
  namespace: media
  labels:
    app: ceph-access-awa
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ceph-access-awa
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ceph-access-awa
    spec:
      containers:
      - image: senk02/ceph-access:latest
        name: ceph-access-awa
        #env:
        #  - name: CEPHFS_USER
        #    valueFrom:
        #      configMapKeyRef:
        #        name: ceph-access-configmap
        #        key: CEPHFS_USER
        #  - name: CEPHFS_FS
        #    value: "awafs"
        #  - name: CEPHFS_MON_ADDR
        #    valueFrom:
        #      configMapKeyRef:
        #        name: ceph-access-configmap
        #        key: CEPHFS_MON_ADDR
        volumeMounts:
          #- name: rook-ceph-admin-keyring
          #  mountPath: "/secret"
          #  subPath: secret
          #  readOnly: true
          - name: ssh-key-config
            mountPath: "/root/.ssh/authorized_keys"
            subPath: authorized_keys
            readOnly: true
          - name: music
            mountPath: "/music"
        ports:
        - containerPort: 22
        #securityContext:
        #  privileged: true
        #  capabilities:
        #    add:
        #      - SYS_ADMIN
        #      - MKNOD
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
            ephemeral-storage: 20Gi
          requests:
            cpu: 10m
            memory: 2Gi
      #volumes:
      #- name: rook-ceph-admin-keyring
      #  secret:
      #    secretName: rook-ceph-admin-keyring
      #    items:
      #    - key: keyring
      #      path: secret
      volumes:
      - name: ssh-key-config
        configMap:
          name: ssh-key-config
      - name: music
        persistentVolumeClaim:
          claimName: sonyx-music-pvc