apiVersion: v1
kind: Service
metadata:
  name: ceph-access-awa
  namespace: media
spec:
  selector:
    app: ceph-access-awa
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
  type: LoadBalancer
