apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.14
    helm:
      valuesObject:
        configs:
          params:
            server.insecure: true
          rbac:
            policy.csv: 
              g, ArgoCD Admin, role:admin
        repoServer:
          rbac:
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["get", "watch", "list"]
        deploymentAnnotations:
          reloader.stakater.com/auto: "true"
        redis-ha:
          enabled: true
          haproxy:
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
        server:
          autoscaling:
            enabled: true
            minReplicas: 2
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
        controller:
          replicas: 1
        applicationSet:
          replicas: 2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true