---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-blogger-warrior
  labels:
    app: archiveteam-blogger-warrior
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: archiveteam-blogger-warrior
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archiveteam-blogger-warrior
    spec:
      containers:
      - image: atdr.meo.ws/archiveteam/blogger-grab
        name: blogger-warrior
        args:
        - --concurrent
        - "1"
        - "Senk0"
        volumeMounts:
        - name: blogger-data
          mountPath: /data
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 48Mi
      volumes:
      - name: blogger-data
        persistentVolumeClaim:
          claimName: archiveteam-blogger-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: archiveteam-blogger-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-youtube-warrior
  labels:
    app: archiveteam-youtube-warrior
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: archiveteam-youtube-warrior
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archiveteam-youtube-warrior
    spec:
      containers:
      - image: atdr.meo.ws/archiveteam/youtube-grab
        name: youtube-warrior
        args:
        - --concurrent
        - "1"
        - "Senk0"
        volumeMounts:
        - name: youtube-data
          mountPath: /data
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 48Mi
      volumes:
      - name: youtube-data
        persistentVolumeClaim:
          claimName: archiveteam-youtube-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: archiveteam-youtube-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-mediafire-warrior
  labels:
    app: archiveteam-mediafire-warrior
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: archiveteam-mediafire-warrior
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archiveteam-mediafire-warrior
    spec:
      containers:
      - image: atdr.meo.ws/archiveteam/mediafire-grab
        name: mediafire-warrior
        args:
        - --concurrent
        - "1"
        - "Senk0"
        volumeMounts:
        - name: mediafire-data
          mountPath: /data
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 48Mi
      volumes:
      - name: mediafire-data
        persistentVolumeClaim:
          claimName: archiveteam-mediafire-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: archiveteam-mediafire-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-pastebin-warrior
  labels:
    app: archiveteam-pastebin-warrior
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: archiveteam-pastebin-warrior
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archiveteam-pastebin-warrior
    spec:
      containers:
      - image: atdr.meo.ws/archiveteam/pastebin-grab
        name: pastebin-warrior
        args:
        - --concurrent
        - "1"
        - "Senk0"
        volumeMounts:
        - name: pastebin-data
          mountPath: /data
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 48Mi
      volumes:
      - name: pastebin-data
        persistentVolumeClaim:
          claimName: archiveteam-pastebin-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: archiveteam-pastebin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiveteam-imgur-warrior
  labels:
    app: archiveteam-imgur-warrior
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: archiveteam-imgur-warrior
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archiveteam-imgur-warrior
    spec:
      containers:
      - image: atdr.meo.ws/archiveteam/imgur-grab
        name: imgur-warrior
        args:
        - --concurrent
        - "1"
        - "Senk0"
        volumeMounts:
        - name: imgur-data
          mountPath: /data
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 48Mi
      volumes:
      - name: imgur-data
        persistentVolumeClaim:
          claimName: archiveteam-imgur-pvc