apiVersion: v1
kind: Service
metadata:
  name: archiveteam-warrior
spec:
  selector:
    app: archiveteam-warrior
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP