apiVersion: apps/v1 
kind: Deployment
metadata:
  name: spacebound
  labels:
    app: spacebound
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: spacebound
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spacebound
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8sw6
      containers:
      - image: itzg/minecraft-server:java8
        name: minecraft
        env:
        - name: EULA
          value: "TRUE"
        - name: TZ
          value: America/Chicago
        - name: TYPE
          value: "FORGE"
        - name: FORGE_VERSION
          value: "14.23.5.2860"
        - name: VERSION
          value: "1.12.2"
        - name: MEMORY
          value: "8G"
        - name: JVM_OPTS
          value: "-Dfml.queryResult=confirm -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+ParallelRefProcEnabled -XX:G1HeapRegionSize=8M"
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - containerPort: 25565
        - containerPort: 25575
        resources:
          limits:
            cpu: 2
            memory: 12Gi
            ephemeral-storage: 4Gi
          requests:
            cpu: 1
            memory: 8Gi
            ephemeral-storage: 64Mi
      volumes:
      - name: data
        hostPath:
          path: /kubernetes/minecraft2/data/
          type: DirectoryOrCreate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spacebound-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 48Gi
  storageClassName: rook-cephfs-hdd
  volumeMode: Filesystem
