apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvc-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kais271.github.io/pvc-exporter/helm3/charts/ # Helm repo URL
    targetRevision: v0.1.4-beta # Chart version
    chart: pvc-exporter # Name of the chart within the repository
    helm:
      valuesObject: # Values to override in the Helm chart
        namespace: monitoring #This is already in the kubectl command, but good to have here too for full control in Argo
  destination:
    server: https://kubernetes.default.svc # The Kubernetes cluster URL
    namespace: monitoring # The namespace where you want to deploy pvc-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
