apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvc-exporter
  namespace: argocd # Ensure this is the namespace where your Argo CD is installed
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default # Or the Argo CD project you want to use
  source:
    repoURL: https://kais271.github.io/pvc-exporter/helm3/charts/ # Helm repo URL
    targetRevision: 0.1.3 # Chart version
    chart: pvc-exporter # Name of the chart within the repository
    helm:
      valuesObject: # Values to override in the Helm chart
        namespace: monitoring
  destination:
    server: https://kubernetes.default.svc # The Kubernetes cluster URL
    namespace: monitoring # The namespace where you want to deploy pvc-exporter
  syncPolicy:
    automated: # Enable auto-sync
      prune: true    # Delete resources no longer defined in Git
      selfHeal: true # Reconcile differences between Git and cluster state
      allowEmpty: false # Prevent deleting all resources in the app
